name: Documentation

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

env:
  ASTRO_SITE: https://bumper.disintegrator.dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # v5.0.0

      - name: Set up Mise
        uses: jdx/mise-action@c53b9236f0b3370f31520f8b142f141256d839c6 # v3.6.0
        with:
          install: true
          cache: true
          env: false

      - name: Prepare cache keys
        run: mise run gha:pre-cache

      - name: Cache Go modules and build cache
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          key: ${{ env.GH_CACHE_GO_KEY }}
          restore-keys: |
            ${{ env.GH_CACHE_GO_KEY }}
            ${{ env.GH_CACHE_GO_KEY_PARTIAL }}
          path: |
            ${{ env.GOCACHE }}
            ${{ env.GOMODCACHE }}
      
      - name: Generate CLI docs
        run: mise run site:cli-reference

      - name: Install, build, and upload your site
        uses: withastro/action@fc88a7002f0c62327f26fb1b15f2a1d581249278 # v5.1.0
        with:
          path: site
          package-manager: bun

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5