name: Create Release PRs

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths: [ .bumper/bump-*.md ]

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    env:
      BUMPER_GROUP: bumper

    steps:
      - name: Checkout repository
        uses: actions/checkout@c2d88d3ecc89a9ef08eebf45d9637801dcee7eb5 # v5.0.0

      - name: Set up Mise
        uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5 # v3.5.1
        with:
          install: true
          cache: true
          env: false

      - name: Set up Bun
        run: bun install --filter=.

      - name: Prepare cache keys
        run: mise run gha:pre-cache

      - name: Cache Go modules and build cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          key: ${{ env.GH_CACHE_GO_KEY }}
          restore-keys: |
            ${{ env.GH_CACHE_GO_KEY }}
            ${{ env.GH_CACHE_GO_KEY_PARTIAL }}
          path: |
            ${{ env.GOCACHE }}
      
      - name: Bumper commit
        run: |
          mise bumper commit
          notes_file="$(mktemp)"
          bumper_version="$(mise bumper current)"
          echo "BUMPER_GROUP_VERSION=$bumper_version" >> $GITHUB_ENV
          echo "RELEASE_NOTES_FILE=$notes_file" >> $GITHUB_ENV
          mise bumper cat --version "$bumper_version" > "$notes_file"
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@22a9089034f40e5a961c8808d113e2c98fb63676 # v7.0.11
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sign-commits: true
          commit-message: 'chore: bumper commit'
          branch: gha/bumper-release
          delete-branch: true
          title: "chore: release bumper v${{ env.BUMPER_GROUP_VERSION }}"
          body-path: ${{ env.RELEASE_NOTES_FILE }}
          reviewers: disintegrator
