name: Create Release PRs

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths: [ .bumper/bump-*.md ]

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    env:
      BUMPER_GROUP: bumper

    steps:
      - name: Checkout repository
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # v5.0.0

      - name: Set up Mise
        uses: jdx/mise-action@c53b9236f0b3370f31520f8b142f141256d839c6 # v3.6.0
        with:
          install: true
          cache: true
          env: false

      - name: Set up Bun
        run: bun install --filter=.

      - name: Prepare cache keys
        run: mise run gha:pre-cache

      - name: Cache Go modules and build cache
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          key: ${{ env.GH_CACHE_GO_KEY }}
          restore-keys: |
            ${{ env.GH_CACHE_GO_KEY }}
            ${{ env.GH_CACHE_GO_KEY_PARTIAL }}
          path: |
            ${{ env.GOCACHE }}
      
      - name: Bumper commit
        run: |
          mise bumper commit
          notes_file="$(mktemp)"
          bumper_version="$(mise bumper current)"
          echo "BUMPER_GROUP_VERSION=$bumper_version" >> $GITHUB_ENV
          echo "RELEASE_NOTES_FILE=$notes_file" >> $GITHUB_ENV
          mise bumper cat --version "$bumper_version" > "$notes_file"
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725 # v8.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sign-commits: true
          commit-message: 'chore: bumper commit'
          branch: gha/bumper-release
          delete-branch: true
          title: "chore: release bumper v${{ env.BUMPER_GROUP_VERSION }}"
          body-path: ${{ env.RELEASE_NOTES_FILE }}
          reviewers: disintegrator
